[project]
name = "sentinel"
version = "0.1.0"
description = "Embedded RISC-V implementation written in Amaranth"
authors = [
    {name = "William D. Jones", email = "thor0505@comcast.net"},
]
dependencies = [
    "m5meta>=1.0.4",
    "m5pre>=1.0.3",
    "amaranth @ git+https://github.com/amaranth-lang/amaranth",
    "tabulate>=0.9.0",
    "amaranth-soc @ git+https://github.com/amaranth-lang/amaranth-soc",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pytest.ini_options]
pythonpath = [
  "src/",
]
markers = [
  "clks: tuple of clocks to register for simulator.",
  "module: top-level module to simulate."
]

[tool.pdm.dev-dependencies]
dev = [
    "flake8>=6.1.0",
    "pytest>=7.4.2",
    "bronzebeard>=0.2.1",
]

[tool.pdm.scripts]
test = { cmd = "pytest" }
gen = { cmd = "amaranth generate {args:sentinel.top:Top} verilog -v -" }
ucode = { call = "m5meta:main" }
bench = { call = "sentinel.bench:main"}
