[project]
name = "sentinel"
version = "0.1.0"
description = "Embedded RISC-V implementation written in Amaranth"
authors = [
    {name = "William D. Jones", email = "thor0505@comcast.net"},
]
dependencies = [
    "m5meta>=1.0.4",
    "m5pre>=1.0.3",
    "amaranth @ git+https://github.com/amaranth-lang/amaranth",
    "tabulate>=0.9.0",
    "amaranth-soc @ git+https://github.com/amaranth-lang/amaranth-soc",
    "bronzebeard>=0.2.1",
    "amaranth-boards @ git+https://github.com/amaranth-lang/amaranth-boards",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pytest.ini_options]
pythonpath = [
  "src/",
]
markers = [
  "clks: tuple of clocks to register for simulator.",
  "module: top-level module to simulate."
]

[tool.pdm.dev-dependencies]
dev = [
    "flake8>=6.1.0",
    "pytest>=7.4.2",
    "doit>=0.36.0",
]

[tool.pdm.scripts]
test = { cmd = "pytest" }
gen = { call = "sentinel.gen:generate" }
demo = { call = "sentinel.gen:demo" }
ucode = { call = "m5meta:main" }
bench = { call = "sentinel.bench:main"}
compile-upstream = { cmd = "doit _dump_tests"}
